In [4]:
import pandas as pd

df = pd.read_csv("../data/resume_data.csv")

print("Dataset Shape:", df.shape)
df.head()

Dataset Shape: (169, 2)

       Category                                             Resume
0  Data Science  Skills * Programming Languages: Python (pandas...
1  Data Science  Education Details \r\nMay 2013 to May 2017 B.E...
2  Data Science  Areas of Interest Deep Learning, Control Syste...
3  Data Science  Skills â¢ R â¢ Python â¢ SAP HANA â¢ Table...
4  Data Science  Education Details \r\n MCA   YMCAUST,  Faridab...

In [5]:
df.columns

Index(['Category', 'Resume'], dtype='str')

In [6]:
import re
import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

def preprocess(text):
    text = str(text).lower()
    text = re.sub(r'\d+', '', text)
    text = re.sub(r'[^\w\s]', '', text)
    words = text.split()
    words = [word for word in words if word not in stop_words]
    return " ".join(words)

df['cleaned_resume'] = df['Resume'].apply(preprocess)

df

[nltk_data] Downloading package stopwords to C:\Users\Kavana S
[nltk_data]     Harthal\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

,Category,Resume,cleaned_resume
0,Data Science,Skills * Programming Languages: Python (pandas...,skills programming languages python pandas num...
1,Data Science,Education Details \r\nMay 2013 to May 2017 B.E...,education details may may uitrgpvdata scientis...
2,Data Science,"Areas of Interest Deep Learning, Control Syste...",areas interest deep learning control system de...
3,Data Science,Skills â¢ R â¢ Python â¢ SAP HANA â¢ Table...,skills â r â python â sap hana â tableau â sap...
4,Data Science,"Education Details \r\n MCA YMCAUST, Faridab...",education details mca ymcaust faridabad haryan...
...,...,...,...
164,Testing,Computer Skills: â¢ Proficient in MS office (...,computer skills â proficient ms office word ba...
165,Testing,â Willingness to accept the challenges. â ...,â willingness accept challenges â positive thi...
166,Testing,"PERSONAL SKILLS â¢ Quick learner, â¢ Eagerne...",personal skills â quick learner â eagerness le...
167,Testing,COMPUTER SKILLS & SOFTWARE KNOWLEDGE MS-Power ...,computer skills software knowledge mspower poi...
168,Testing,Skill Set OS Windows XP/7/8/8.1/10 Database MY...,skill set os windows xp database mysql sql ser...

In [7]:
import unicodedata

def preprocess(text):

    text = str(text)

    # Fix encoding issues
    text = unicodedata.normalize("NFKD", text)
    text = text.encode("ascii", "ignore").decode("utf-8", "ignore")

    # Lowercase
    text = text.lower()

    # Remove numbers
    text = re.sub(r'\d+', '', text)

    # Remove special characters
    text = re.sub(r'[^\w\s]', '', text)

    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()

    # Remove stopwords
    words = text.split()
    words = [word for word in words if word not in stop_words]

    return " ".join(words)

In [8]:
df['cleaned_resume'] = df['Resume'].apply(preprocess)

In [9]:
# ================================
# Dataset Cleaning Verification
# ================================

import re

print("Checking cleaned dataset...\n")

# 1. Compare original and cleaned resume
index = 0

print("Original Resume (first 500 characters):\n")
print(df['Resume'][index][:500])

print("\nCleaned Resume (first 500 characters):\n")
print(df['cleaned_resume'][index][:500])
print("\n---------------------------------------\n")

# 2. Check if numbers still exist
numbers_left = df['cleaned_resume'].apply(lambda x: bool(re.search(r'\d', x))).sum()
print("Number of resumes containing digits:", numbers_left)

# 3. Check if special characters still exist
special_chars_left = df['cleaned_resume'].apply(lambda x: bool(re.search(r'[^\w\s]', x))).sum()
print("Number of resumes containing special characters:", special_chars_left)

# 4. Check if all text is lowercase
all_lowercase = df['cleaned_resume'].apply(lambda x: x.islower()).all()
print("All resumes are lowercase:", all_lowercase)

# 5. Check for empty resumes
empty_rows = df['cleaned_resume'].apply(lambda x: len(x.strip()) == 0).sum()
print("Number of empty cleaned resumes:", empty_rows)

print("\nVerification completed.")

Checking cleaned dataset...

Original Resume (first 500 characters):

Skills * Programming Languages: Python (pandas, numpy, scipy, scikit-learn, matplotlib), Sql, Java, JavaScript/JQuery. * Machine learning: Regression, SVM, NaÃ¯ve Bayes, KNN, Random Forest, Decision Trees, Boosting techniques, Cluster Analysis, Word Embedding, Sentiment Analysis, Natural Language processing, Dimensionality reduction, Topic Modelling (LDA, NMF), PCA & Neural Nets. * Database Visualizations: Mysql, SqlServer, Cassandra, Hbase, ElasticSearch D3.js, DC.js, Plotly, kibana, matplotlib

Cleaned Resume (first 500 characters):

skills programming languages python pandas numpy scipy scikitlearn matplotlib sql java javascriptjquery machine learning regression svm naa bayes knn random forest decision trees boosting techniques cluster analysis word embedding sentiment analysis natural language processing dimensionality reduction topic modelling lda nmf pca neural nets database visualizations mysql sqlserver cassandra hbase elasticsearch djs dcjs plotly kibana matplotlib ggplot tableau others regular expression html css ang

---------------------------------------

Number of resumes containing digits: 0
Number of resumes containing special characters: 0
All resumes are lowercase: True
Number of empty cleaned resumes: 0

Verification completed.

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=3000)

X = tfidf.fit_transform(df['cleaned_resume'])

X.shape

In [10]:
df

,Category,Resume,cleaned_resume
0,Data Science,Skills * Programming Languages: Python (pandas...,skills programming languages python pandas num...
1,Data Science,Education Details \r\nMay 2013 to May 2017 B.E...,education details may may uitrgpvdata scientis...
2,Data Science,"Areas of Interest Deep Learning, Control Syste...",areas interest deep learning control system de...
3,Data Science,Skills â¢ R â¢ Python â¢ SAP HANA â¢ Table...,skills r python sap hana tableau sap hana sql ...
4,Data Science,"Education Details \r\n MCA YMCAUST, Faridab...",education details mca ymcaust faridabad haryan...
...,...,...,...
164,Testing,Computer Skills: â¢ Proficient in MS office (...,computer skills proficient ms office word basi...
165,Testing,â Willingness to accept the challenges. â ...,willingness accept challenges positive thinkin...
166,Testing,"PERSONAL SKILLS â¢ Quick learner, â¢ Eagerne...",personal skills quick learner eagerness learn ...
167,Testing,COMPUTER SKILLS & SOFTWARE KNOWLEDGE MS-Power ...,computer skills software knowledge mspower poi...
168,Testing,Skill Set OS Windows XP/7/8/8.1/10 Database MY...,skill set os windows xp database mysql sql ser...

In [11]:
#for saving the cleaned dataset
df.to_csv("cleaned_resume_dataset.csv", index=False)